services:
  mariadb-backup:
    # https://github.com/fradelg/docker-mysql-cron-backup
    # https://hub.docker.com/r/fradelg/mysql-cron-backup
    image: fradelg/mysql-cron-backup
    networks:
      - dbs
    depends_on:
      - mariadb
    volumes:
      - ./data/backup/mariadb:/backup
    environment:
      - MYSQL_HOST=mariadb
      - MYSQL_USER=root
      - MYSQL_PASS=${MARIADB_ROOT_PASSWORD}
      - MAX_BACKUPS=7
      - INIT_BACKUP=0
      - INIT_RESTORE_LATEST=0
      - CRON_TIME=0 0 * * *
    restart: unless-stopped
